export function EULAContent() {
  return (
    <div className="space-y-4 pr-4 text-sm text-muted-foreground">
      <p>
        <strong className="text-foreground">Effective Date:</strong> February 1,
        2026
      </p>
      <p>
        This End User License Agreement (&quot;EULA&quot; or
        &quot;Agreement&quot;) is a legal agreement between you (&quot;you&quot;
        or &quot;User&quot;) and MyFusion Solutions, LLC (&quot;MyFusion,&quot;
        &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) governing your use of
        the MyFusion Helper platform at myfusionhelper.ai, including all
        associated software, features, and services (the &quot;Software&quot;).
      </p>

      {/* 1. Agreement */}
      <h3 className="font-semibold text-foreground">1. Agreement</h3>
      <p>
        By installing, accessing, or using the Software, you acknowledge that
        you have read, understood, and agree to be bound by the terms of this
        EULA. If you are entering into this Agreement on behalf of a company or
        other legal entity, you represent that you have the authority to bind
        that entity to this Agreement. If you do not agree to these terms, do
        not use the Software.
      </p>

      {/* 2. License Grant */}
      <h3 className="font-semibold text-foreground">2. License Grant</h3>
      <p>
        Subject to your compliance with this Agreement and payment of applicable
        fees, MyFusion grants you a limited, non-exclusive, non-transferable,
        non-sublicensable, revocable license to access and use the Software
        during the term of your subscription solely for your internal business
        purposes.
      </p>
      <p>
        This license is provided on a software-as-a-service basis. You do not
        receive a copy of the Software; rather, you are granted the right to
        access and use the Software remotely through the internet. The license
        is personal to you and your organization and may not be shared with or
        transferred to third parties.
      </p>

      {/* 3. Restrictions */}
      <h3 className="font-semibold text-foreground">3. Restrictions</h3>
      <p>You agree that you will not, and will not permit any third party to:</p>
      <ul className="ml-6 list-disc space-y-1">
        <li>
          Copy, modify, adapt, translate, or create derivative works based on
          the Software.
        </li>
        <li>
          Reverse engineer, decompile, disassemble, or otherwise attempt to
          derive the source code, algorithms, or underlying structure of the
          Software.
        </li>
        <li>
          Rent, lease, lend, sell, sublicense, distribute, or otherwise transfer
          access to the Software to any third party.
        </li>
        <li>
          Use the Software to build a competing product or service, or to
          benchmark the Software against a competing product or service.
        </li>
        <li>
          Use automated tools, bots, or scripts to scrape, extract, or harvest
          data from the Software, except through our published APIs and in
          compliance with our rate limits.
        </li>
        <li>
          Remove, alter, or obscure any proprietary notices, labels, or
          markings on the Software.
        </li>
        <li>
          Use the Software in any manner that violates applicable laws or
          regulations, or in any way that could damage, disable, overburden, or
          impair the Software.
        </li>
        <li>
          Share login credentials or allow multiple individuals to access the
          Software through a single account, except as expressly permitted by
          your subscription plan.
        </li>
      </ul>

      {/* 4. AI Features */}
      <h3 className="font-semibold text-foreground">4. AI Features</h3>
      <p>
        The Software includes AI-powered features that use artificial
        intelligence and machine learning to generate content, provide
        suggestions, and assist with workflow optimization (&quot;AI
        Features&quot;). Your use of AI Features is subject to the following
        terms:
      </p>
      <p>
        <strong className="text-foreground">
          AI outputs are tools, not advice.
        </strong>{" "}
        All content, suggestions, and outputs generated by AI Features are
        intended as productivity tools and starting points. They do not
        constitute professional advice of any kind, including but not limited to
        legal, financial, medical, or business advice. You should not rely on AI
        outputs as a substitute for your own judgment or the guidance of
        qualified professionals.
      </p>
      <p>
        <strong className="text-foreground">
          User review is required.
        </strong>{" "}
        You are solely responsible for reviewing, editing, and approving all
        AI-generated content before publishing, sending, or otherwise using it.
        By using AI-generated content, you assume full responsibility for that
        content and any consequences of its use.
      </p>
      <p>
        <strong className="text-foreground">
          AI may produce inaccurate results.
        </strong>{" "}
        AI technology is inherently probabilistic and may generate outputs that
        are inaccurate, incomplete, misleading, or inappropriate. We make no
        representations or warranties regarding the accuracy, reliability,
        completeness, or suitability of any AI-generated output. You acknowledge
        this limitation and agree to use AI Features accordingly.
      </p>

      {/* 5. Ownership */}
      <h3 className="font-semibold text-foreground">5. Ownership</h3>
      <p>
        <strong className="text-foreground">MyFusion&apos;s ownership.</strong>{" "}
        MyFusion and its licensors retain all right, title, and interest in and
        to the Software, including all intellectual property rights therein.
        This includes the Software&apos;s source code, design, architecture,
        documentation, algorithms, AI models and configurations, user interface,
        and all related proprietary technology. This Agreement does not convey
        any ownership rights in the Software to you.
      </p>
      <p>
        <strong className="text-foreground">Your data.</strong> You retain all
        right, title, and interest in and to the data you submit to the Software
        (&quot;Your Data&quot;). You grant MyFusion a limited, non-exclusive
        license to use, process, and store Your Data solely to provide and
        improve the Software. We will not use Your Data for any purpose other
        than delivering the Service to you, except in aggregated and anonymized
        form that cannot identify you.
      </p>

      {/* 6. Confidentiality */}
      <h3 className="font-semibold text-foreground">6. Confidentiality</h3>
      <p>
        Each party agrees to maintain the confidentiality of any non-public
        information received from the other party that is designated as
        confidential or that reasonably should be understood to be confidential
        (&quot;Confidential Information&quot;). Confidential Information includes
        but is not limited to business strategies, customer data, technical
        specifications, and proprietary methods.
      </p>
      <p>
        Neither party shall disclose the other&apos;s Confidential Information
        to any third party except to employees, contractors, or agents who need
        to know such information and who are bound by confidentiality
        obligations at least as protective as those in this Agreement. This
        obligation of confidentiality does not apply to information that is
        publicly available, independently developed, or rightfully received from
        a third party without restriction.
      </p>

      {/* 7. Fees & Payment */}
      <h3 className="font-semibold text-foreground">7. Fees and Payment</h3>
      <p>
        Your use of the Software requires a paid subscription. Subscription
        plans, pricing, and payment terms are described in our{" "}
        <a href="/terms" className="text-primary underline">
          Terms of Service
        </a>
        . By subscribing, you agree to pay all applicable fees in accordance
        with the billing terms in effect at the time of each payment.
      </p>
      <p>
        Failure to pay fees when due may result in suspension or termination of
        your access to the Software. All fees are exclusive of applicable taxes,
        which you are responsible for paying.
      </p>

      {/* 8. Term & Termination */}
      <h3 className="font-semibold text-foreground">
        8. Term and Termination
      </h3>
      <p>
        This Agreement is effective as of the date you first access or use the
        Software and continues until terminated. Either party may terminate this
        Agreement by providing thirty (30) days&apos; written notice to the
        other party.
      </p>
      <p>
        We may terminate or suspend your access immediately if you breach any
        material term of this Agreement, engage in conduct that threatens the
        security or integrity of the Software, or fail to pay applicable fees
        after reasonable notice.
      </p>
      <p>
        Upon termination, your license to use the Software ceases immediately.
        Your Data will remain available for export for thirty (30) days
        following termination. After this period, we may permanently delete Your
        Data from our systems. Termination does not relieve you of the
        obligation to pay any fees that accrued prior to the termination date.
      </p>

      {/* 9. Warranty Disclaimer */}
      <h3 className="font-semibold text-foreground">
        9. Warranty Disclaimer
      </h3>
      <p>
        The Software is provided &quot;as is&quot; and &quot;as available&quot;
        without warranties of any kind, whether express, implied, or statutory.
        MyFusion disclaims all warranties, including but not limited to implied
        warranties of merchantability, fitness for a particular purpose, title,
        and non-infringement.
      </p>
      <p>
        We do not warrant that the Software will meet your specific
        requirements, operate without interruption or error, be compatible with
        all third-party services, or produce accurate or reliable AI-generated
        outputs. Any reliance on the Software or its outputs is at your own
        risk.
      </p>

      {/* 10. Limitation of Liability */}
      <h3 className="font-semibold text-foreground">
        10. Limitation of Liability
      </h3>
      <p>
        To the maximum extent permitted by applicable law, MyFusion shall not be
        liable for any indirect, incidental, special, consequential, or punitive
        damages, or any loss of profits, revenue, data, or business
        opportunities, arising out of or related to this Agreement or your use
        of the Software, regardless of the theory of liability.
      </p>
      <p>
        MyFusion&apos;s total aggregate liability for all claims arising out of
        or related to this Agreement shall not exceed the total fees you paid to
        MyFusion during the six (6) months immediately preceding the event
        giving rise to the liability. This cap applies regardless of whether the
        claim is based in contract, tort, strict liability, or any other legal
        theory.
      </p>

      {/* 11. Indemnification */}
      <h3 className="font-semibold text-foreground">11. Indemnification</h3>
      <p>
        You agree to indemnify, defend, and hold harmless MyFusion Solutions,
        LLC, its officers, directors, employees, agents, and affiliates from and
        against any and all claims, liabilities, damages, losses, costs, and
        expenses (including reasonable attorneys&apos; fees) arising out of or
        related to:
      </p>
      <ul className="ml-6 list-disc space-y-1">
        <li>
          Your use of the Software in violation of this Agreement.
        </li>
        <li>
          Your use of AI-generated content, including any claims arising from
          content you publish, distribute, or otherwise use.
        </li>
        <li>
          Your violation of any applicable law, regulation, or third-party
          rights.
        </li>
        <li>
          Any data you submit to the Software that infringes the intellectual
          property or privacy rights of a third party.
        </li>
      </ul>
      <p>
        MyFusion will provide you with prompt written notice of any such claim
        and will cooperate reasonably with your defense of the claim.
      </p>

      {/* 12. General Provisions */}
      <h3 className="font-semibold text-foreground">
        12. General Provisions
      </h3>
      <p>
        <strong className="text-foreground">Assignment.</strong> You may not
        assign or transfer this Agreement or any of your rights or obligations
        hereunder without our prior written consent. MyFusion may assign this
        Agreement in connection with a merger, acquisition, or sale of all or
        substantially all of its assets.
      </p>
      <p>
        <strong className="text-foreground">Governing law.</strong> This
        Agreement is governed by and construed in accordance with the laws of
        the State of Florida, without regard to its conflict of law provisions.
        Any disputes arising under this Agreement shall be resolved in
        accordance with the dispute resolution provisions set forth in our Terms
        of Service.
      </p>
      <p>
        <strong className="text-foreground">Severability.</strong> If any
        provision of this Agreement is found to be unenforceable or invalid, that
        provision shall be limited or eliminated to the minimum extent necessary
        so that the remaining provisions of this Agreement remain in full force
        and effect.
      </p>
      <p>
        <strong className="text-foreground">Entire agreement.</strong> This
        Agreement, together with our Terms of Service and Privacy Policy,
        constitutes the entire agreement between you and MyFusion with respect
        to the Software and supersedes all prior or contemporaneous
        communications, proposals, and agreements, whether oral or written.
      </p>
      <p>
        <strong className="text-foreground">Waiver.</strong> The failure of
        either party to enforce any right or provision of this Agreement shall
        not constitute a waiver of that right or provision. Any waiver must be
        in writing and signed by the waiving party.
      </p>
      <p>
        <strong className="text-foreground">Force majeure.</strong> Neither party
        shall be liable for any failure or delay in performance due to
        circumstances beyond its reasonable control, including but not limited to
        natural disasters, acts of government, internet outages, or failures of
        third-party services.
      </p>

      {/* 13. Contact */}
      <h3 className="font-semibold text-foreground">
        13. Contact Information
      </h3>
      <p>
        If you have any questions about this EULA, please contact us:
      </p>
      <p>
        MyFusion Solutions, LLC
        <br />
        3030 N. Rocky Point Dr., STE 150A
        <br />
        Tampa, FL 33607
        <br />
        Legal inquiries:{" "}
        <a
          href="mailto:legal@myfusionsolutions.com"
          className="text-primary underline"
        >
          legal@myfusionsolutions.com
        </a>
        <br />
        Support:{" "}
        <a
          href="mailto:help@myfusionsolutions.com"
          className="text-primary underline"
        >
          help@myfusionsolutions.com
        </a>
      </p>
    </div>
  )
}
