import {
  Tag,
  Copy,
  Calculator,
  Calendar,
  Bell,
  FileSpreadsheet,
  Webhook,
  Users,
  Eraser,
  Merge,
  ArrowRightLeft,
  Type,
  Hash,
  Lock,
  Search,
  UserCheck,
  Building2,
  Split,
  Target,
  Zap,
  Link2,
  Play,
  Clock,
  Repeat,
  Mail,
  MessageSquare,
  FileText,
  BarChart3,
  DollarSign,
  Globe,
  Phone,
  Scissors,
  ArrowDown,
  ArrowUp,
  CheckCircle,
  XCircle,
  Percent,
  StickyNote,
  Shield,
  Video,
  CalendarClock,
  ListChecks,
  Layers,
  ToggleLeft,
  Grip,
  Camera,
  Crown,
  MousePointerClick,
  MailOpen,
  Send,
  GitBranch,
  RefreshCw,
  type LucideIcon,
} from 'lucide-react'

export interface HelperDefinition {
  id: string
  name: string
  description: string
  category: HelperCategory
  icon: LucideIcon
  popular: boolean
  status: 'available' | 'coming_soon' | 'beta'
  requiresCRM: boolean
  supportedCRMs: string[] // empty = all
}

export type HelperCategory =
  | 'contact'
  | 'data'
  | 'tagging'
  | 'automation'
  | 'integration'
  | 'notification'
  | 'analytics'

export interface CategoryInfo {
  id: string
  name: string
  description: string
}

export const categoryInfo: CategoryInfo[] = [
  { id: 'all', name: 'All Helpers', description: 'Browse all available helpers' },
  { id: 'contact', name: 'Contact', description: 'Manage and manipulate contact data' },
  { id: 'data', name: 'Data', description: 'Transform, format, and calculate field values' },
  { id: 'tagging', name: 'Tagging', description: 'Apply, remove, and manage tags' },
  { id: 'automation', name: 'Automation', description: 'Trigger sequences, goals, and workflows' },
  { id: 'integration', name: 'Integration', description: 'Connect to external services' },
  { id: 'notification', name: 'Notification', description: 'Send alerts and messages' },
  { id: 'analytics', name: 'Analytics', description: 'Calculate metrics and scores' },
]

export const helpersCatalog: HelperDefinition[] = [
  // ========== CONTACT HELPERS ==========
  {
    id: 'copy_it',
    name: 'Copy It',
    description: 'Copy a field value from one field to another on a contact',
    category: 'contact',
    icon: Copy,
    popular: true,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'assign_it',
    name: 'Assign It',
    description: 'Assign a contact to a specific owner or team member',
    category: 'contact',
    icon: UserCheck,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'merge_it',
    name: 'Merge It',
    description: 'Merge values from multiple fields into a single target field',
    category: 'contact',
    icon: Merge,
    popular: true,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'field_to_field',
    name: 'Field to Field',
    description: 'Map multiple source fields to target fields in one operation',
    category: 'contact',
    icon: ArrowRightLeft,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'clear_it',
    name: 'Clear It',
    description: 'Clear one or more field values to empty',
    category: 'contact',
    icon: Eraser,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'combine_it',
    name: 'Combine It',
    description: 'Combine multiple fields into a single field with a separator',
    category: 'contact',
    icon: Layers,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'move_it',
    name: 'Move It',
    description: 'Move a field value to another field and clear the source',
    category: 'contact',
    icon: ArrowRightLeft,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'found_it',
    name: 'Found It',
    description: 'Check if a field is populated and branch with tags or goals',
    category: 'contact',
    icon: Search,
    popular: true,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'name_parse_it',
    name: 'Name Parse It',
    description: 'Parse a full name into first name, last name, and suffix',
    category: 'contact',
    icon: Users,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'company_link',
    name: 'Company Link',
    description: 'Link a contact to a company record or create one',
    category: 'contact',
    icon: Building2,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: ['keap'],
  },
  {
    id: 'opt_in',
    name: 'Simple Opt-In',
    description: 'Opt a contact email into marketing communications',
    category: 'contact',
    icon: CheckCircle,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: ['keap'],
  },
  {
    id: 'opt_out',
    name: 'Simple Opt-Out',
    description: 'Opt a contact email out of marketing communications',
    category: 'contact',
    icon: XCircle,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: ['keap'],
  },
  {
    id: 'note_it',
    name: 'Note It',
    description: 'Add a note or comment to a contact record with template support',
    category: 'contact',
    icon: StickyNote,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'default_to_field',
    name: 'Default to Field',
    description: 'Set default values in fields only if they are empty',
    category: 'contact',
    icon: FileText,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },

  {
    id: 'own_it',
    name: 'Own It',
    description: 'Set the contact owner/assignee based on rules or round-robin',
    category: 'contact',
    icon: Crown,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'snapshot_it',
    name: 'Snapshot It',
    description: 'Capture a snapshot of all contact data for audit or backup',
    category: 'contact',
    icon: Camera,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },

  // ========== DATA HELPERS ==========
  {
    id: 'format_it',
    name: 'Format It',
    description: 'Format field values: uppercase, lowercase, title case, and more',
    category: 'data',
    icon: Type,
    popular: true,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'math_it',
    name: 'Math It',
    description: 'Perform math operations: add, subtract, multiply, divide, round',
    category: 'data',
    icon: Calculator,
    popular: true,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'date_calc',
    name: 'Date Calculator',
    description: 'Calculate dates: add/subtract days, find differences, format dates',
    category: 'data',
    icon: Calendar,
    popular: true,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'text_it',
    name: 'Text It',
    description: 'Text manipulation: prepend, append, replace, extract, truncate',
    category: 'data',
    icon: Type,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'password_it',
    name: 'Password It',
    description: 'Generate secure random passwords and store in a contact field',
    category: 'data',
    icon: Lock,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'word_count_it',
    name: 'Word Count It',
    description: 'Count words or characters in a field and store the result',
    category: 'data',
    icon: Hash,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'split_it',
    name: 'Split It',
    description: 'A/B split testing: alternate between two groups on each run',
    category: 'data',
    icon: Split,
    popular: true,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'when_is_it',
    name: 'When Is It',
    description: 'Convert dates between timezones and format output',
    category: 'data',
    icon: CalendarClock,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },

  {
    id: 'get_the_first',
    name: 'Get The First',
    description: 'Extract the first value from a delimited field',
    category: 'data',
    icon: ArrowUp,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'get_the_last',
    name: 'Get The Last',
    description: 'Extract the last value from a delimited field',
    category: 'data',
    icon: ArrowDown,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'split_it_basic',
    name: 'Split It Basic',
    description: 'Split a field value by delimiter and store parts in separate fields',
    category: 'data',
    icon: Scissors,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'last_click_it',
    name: 'Last Click It',
    description: 'Track and store the last email click timestamp for a contact',
    category: 'data',
    icon: MousePointerClick,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: ['keap'],
  },
  {
    id: 'last_open_it',
    name: 'Last Open It',
    description: 'Track and store the last email open timestamp for a contact',
    category: 'data',
    icon: MailOpen,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: ['keap'],
  },
  {
    id: 'last_send_it',
    name: 'Last Send It',
    description: 'Track and store the last email send timestamp for a contact',
    category: 'data',
    icon: Send,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: ['keap'],
  },

  // ========== TAGGING HELPERS ==========
  {
    id: 'tag_it',
    name: 'Tag It',
    description: 'Apply or remove tags from a contact',
    category: 'tagging',
    icon: Tag,
    popular: true,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'clear_tags',
    name: 'Clear Tags',
    description: 'Remove tags by ID, prefix, category, or remove all tags',
    category: 'tagging',
    icon: Eraser,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'group_it',
    name: 'Group It',
    description: 'Create and assign tags dynamically based on field values',
    category: 'tagging',
    icon: Grip,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'count_tags',
    name: 'Count Tags',
    description: 'Count how many tags a contact has and store the result',
    category: 'tagging',
    icon: Hash,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'score_it',
    name: 'Score It',
    description: 'Calculate a lead score based on tag-based scoring rules',
    category: 'tagging',
    icon: Target,
    popular: true,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },

  {
    id: 'count_it_tags',
    name: 'Count It Tags',
    description: 'Count tags matching a pattern or prefix and store the result',
    category: 'tagging',
    icon: Hash,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },

  // ========== AUTOMATION HELPERS ==========
  {
    id: 'trigger_it',
    name: 'Trigger It',
    description: 'Trigger an automation, campaign, or workflow sequence',
    category: 'automation',
    icon: Play,
    popular: true,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'goal_it',
    name: 'Goal It',
    description: 'Achieve a campaign goal or milestone for a contact',
    category: 'automation',
    icon: Target,
    popular: true,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: ['keap'],
  },
  {
    id: 'action_it',
    name: 'Action It',
    description: 'Run multiple automations or action sequences in order',
    category: 'automation',
    icon: ListChecks,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'drip_it',
    name: 'Drip It',
    description: 'Manage drip campaign steps with automatic progression',
    category: 'automation',
    icon: Repeat,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'chain_it',
    name: 'Chain It',
    description: 'Chain multiple helpers together to run in sequence',
    category: 'automation',
    icon: Link2,
    popular: true,
    status: 'available',
    requiresCRM: false,
    supportedCRMs: [],
  },
  {
    id: 'stage_it',
    name: 'Stage It',
    description: 'Match opportunities by stage and update them with goal triggers',
    category: 'automation',
    icon: Layers,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: ['keap'],
  },
  {
    id: 'timezone_triggers',
    name: 'Timezone Triggers',
    description: 'Trigger automations at specific times in the contact timezone',
    category: 'automation',
    icon: Clock,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },

  // ========== HUBSPOT HELPERS ==========
  {
    id: 'hubspot_deal_stager',
    name: 'Deal Stager',
    description: 'Move deals through pipeline stages based on contact activity or field values',
    category: 'automation',
    icon: Layers,
    popular: true,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: ['hubspot'],
  },
  {
    id: 'hubspot_list_sync',
    name: 'List Sync',
    description: 'Sync contacts between HubSpot lists based on criteria and field mappings',
    category: 'contact',
    icon: RefreshCw,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: ['hubspot'],
  },
  {
    id: 'hubspot_property_mapper',
    name: 'Property Mapper',
    description: 'Map and transform custom properties across HubSpot objects',
    category: 'data',
    icon: ArrowRightLeft,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: ['hubspot'],
  },
  {
    id: 'hubspot_workflow_trigger',
    name: 'Workflow Trigger',
    description: 'Trigger HubSpot workflows based on external conditions or schedules',
    category: 'automation',
    icon: GitBranch,
    popular: true,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: ['hubspot'],
  },

  // ========== INTEGRATION HELPERS ==========
  {
    id: 'google_sheet_it',
    name: 'Google Sheet It',
    description: 'Sync contact data to and from Google Sheets',
    category: 'integration',
    icon: FileSpreadsheet,
    popular: true,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'slack_it',
    name: 'Slack It',
    description: 'Send messages and notifications to Slack channels',
    category: 'integration',
    icon: MessageSquare,
    popular: true,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'hook_it',
    name: 'Hook It',
    description: 'Send contact data to external webhooks and APIs',
    category: 'integration',
    icon: Webhook,
    popular: true,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'excel_it',
    name: 'Excel It',
    description: 'Export contact data to Excel spreadsheets',
    category: 'integration',
    icon: FileSpreadsheet,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'mail_it',
    name: 'Mail It',
    description: 'Send custom emails with templates and field merging',
    category: 'integration',
    icon: Mail,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'phone_lookup',
    name: 'Phone Lookup',
    description: 'Validate and enrich phone numbers with carrier data',
    category: 'integration',
    icon: Phone,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'email_validate_it',
    name: 'Email Validate',
    description: 'Validate email addresses for deliverability',
    category: 'integration',
    icon: Shield,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'zoom_webinar',
    name: 'Zoom Webinar',
    description: 'Register contacts for Zoom webinars automatically',
    category: 'integration',
    icon: Video,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'calendly_it',
    name: 'Calendly',
    description: 'Sync Calendly events and registrations with contacts',
    category: 'integration',
    icon: CalendarClock,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },

  // ========== NOTIFICATION HELPERS ==========
  {
    id: 'notify_me',
    name: 'Notify Me',
    description: 'Send notifications via email, Slack, or webhook',
    category: 'notification',
    icon: Bell,
    popular: true,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'twilio_sms',
    name: 'Twilio SMS',
    description: 'Send SMS messages via Twilio with field merge',
    category: 'notification',
    icon: MessageSquare,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
  {
    id: 'email_engagement',
    name: 'Email Engagement',
    description: 'Track email opens, clicks, and trigger automations',
    category: 'notification',
    icon: Mail,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: ['keap'],
  },

  // ========== ANALYTICS HELPERS ==========
  {
    id: 'rfm_calculation',
    name: 'RFM Calculation',
    description: 'Calculate Recency, Frequency, Monetary scores for segmentation',
    category: 'analytics',
    icon: BarChart3,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: ['keap'],
  },
  {
    id: 'customer_lifetime_value',
    name: 'Customer Lifetime Value',
    description: 'Calculate customer lifetime value and average order metrics',
    category: 'analytics',
    icon: DollarSign,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: ['keap'],
  },
  {
    id: 'ip_location',
    name: 'IP Location',
    description: 'Detect contact location from IP address for geo-targeting',
    category: 'analytics',
    icon: Globe,
    popular: false,
    status: 'available',
    requiresCRM: true,
    supportedCRMs: [],
  },
]

export function getHelpersByCategory(category: string): HelperDefinition[] {
  if (category === 'all') return helpersCatalog
  return helpersCatalog.filter((h) => h.category === category)
}

export function getCategoryCounts(): Record<string, number> {
  const counts: Record<string, number> = { all: helpersCatalog.length }
  for (const helper of helpersCatalog) {
    counts[helper.category] = (counts[helper.category] || 0) + 1
  }
  return counts
}
